package com.csidigital.shared.enumeration;

public enum Currency {
    AFN("AFN - Afghan-Afghani"),
    AMD("AMD - Armenian Dram"),
    AUD("AUD - Australian Dollar"),
    BSD("BSD - Bahamian Dollar"),
    BBD("BBD - Barbadian Dollar"),
    BZD("BZD - Belize Dollar"),
    BMD("BMD - Bermudian Dollar"),
    BND("BND - Brunei Dollar"),
    BIF("BIF - Burundian Franc"),
    KHR("KHR - Cambodian Riel"),
    CAD("CAD - Canadian Dollar"),
    CVE("CVE - Cape Verdean Escudo"),
    KYD("KYD - Cayman Islands Dollar"),
    XAF("XAF - Central African CFA Franc"),
    XPF("XPF - CFP Franc"),
    CLP("CLP - Chilean Peso"),
    CNY("CNY - Chinese Yuan Renminbi"),
    COP("COP - Colombian Peso"),
    KMF("KMF - Comorian Franc"),
    CRC("CRC - Costa Rican Colón"),
    HRK("HRK - Croatian Kuna"),
    CZK("CZK - Czech Koruna"),
    DKK ( "DKK - Danish Krone"),
    DJF ( "DJF - Djiboutian Franc"),
    DOP ( "DOP - Dominican Peso"),
    EGP ( "EGP - Egyptian Pound"),
    ETB ( "ETB - Ethiopian Birr"),
    EUR ( "EUR - Euro"),
    FKP ( "FKP - Falkland Islands Pound"),
    FJD ( "FJD - Fijian Dollar"),
    GMD ( "GMD - Gambian Dalasi"),
    GEL ( "GEL - Georgian Lari"),
    GHS ( "GHS - Ghanaian Cedi"),
    GIP ( "GIP - Gibraltar Pound"),
    GTQ ( "GTQ - Guatemalan Quetzal"),
    GNF ( "GNF - Guinean Franc"),
    GYD ( "GYD - Guyanese Dollar"),
    HTG ( "HTG - Haitian Gourde"),
    HNL ( "HNL - Honduran Lempira"),
    HKD ( "HKD - Hong Kong Dollar"),
    HUF ( "HUF - Hungarian Forint"),
    ISK ( "ISK - Icelandic Króna"),
    INR ( "INR - Indian Rupee"),
    IDR ( "IDR - Indonesian Rupiah"),
    IRR ( "IRR - Iranian Rial"),
    IQD ( "IQD - Iraqi Dinar"),
    ILS ( "ILS - Israeli New Shekel"),
    JPY ( "JPY - Japanese Yen"),
    JOD ( "JOD - Jordanian Dinar"),
    KZT ( "KZT - Kazakhstani Tenge"),
    KES ( "KES - Kenyan Shilling"),
    KWD ( "KWD - Kuwaiti Dinar"),
    LAK ( "LAK - Lao Kip"),
    LBP ( "LBP - Lebanese Pound"),
    LRD ( "LRD - Liberian Dollar"),
    MGA ( "MGA - Malagasy Ariary"),
    MWK ( "MWK - Malawian Kwacha"),
    MYR ( "MYR - Malaysian Ringgit"),
    MUR ( "MUR - Mauritian Rupee"),
    MXN ( "MXN - Mexican Peso"),
    MDL ( "MDL - Moldovan Leu"),
    MNT ( "MNT - Mongolian Tugrik"),
    MAD ( "MAD - Moroccan Dirham"),
    MZN ( "MZN - Mozambican Metical"),
    MMK ( "MMK - Myanmar Kyat"),
    NAD ( "NAD - Namibian Dollar"),
    NPR ( "NPR - Nepalese Rupee"),
    ANG ( "ANG - Netherlands Antillean Guilder"),
    NZD ( "NZD - New Zealand Dollar"),
    NIO ( "NIO - Nicaraguan Córdoba"),
    NGN ( "NGN - Nigerian Naira"),
    NOK ( "NOK - Norwegian Krone"),
    OMR ( "OMR - Omani Rial"),
    PKR ( "PKR - Pakistani Rupee"),
    PAB ( "PAB - Panamanian Balboa"),
    PGK ( "PGK - Papua New Guinean Kina"),
    PYG ( "PYG - Paraguayan Guaraní"),
    PEN ( "PEN - Peruvian Sol"),
    PHP ( "PHP - Philippine Peso"),
    PLN ( "PLN - Polish Złoty"),
    QAR ( "QAR - Qatari Riyal"),
    RON ( "RON - Romanian Leu"),
    RUB ( "RUB - Russian Ruble"),
    RWF ( "RWF - Rwandan Franc"),
    SHP ( "SHP - Saint Helena Pound"),
    SVC ( "SVC - Salvadoran Colón"),
    SAR ( "SAR - Saudi Riyal"),
    RSD ( "RSD - Serbian Dinar"),
    SCR ( "SCR - Seychelles Rupee"),
    SLL ( "SLL - Sierra Leonean Leone"),
    SGD ( "SGD - Singapore Dollar"),
    SOS ( "SOS - Somali Shilling"),
    ZAR ( "ZAR - South African Rand"),
    KRW ( "KRW - South Korean Won"),
    SSP ( "SSP - South Sudanese Pound"),
    LKR ( "LKR - Sri Lankan Rupee"),
    SDG ( "SDG - Sudanese Pound"),
    SRD ( "SRD - Surinamese Dollar"),
    SZL ( "SZL - Swazi Lilangeni"),
    SEK ( "SEK - Swedish Krona"),
    CHF ( "CHF - Swiss Franc"),
    SYP ( "SYP - Syrian Pound"),
    TWD ( "TWD - New Taiwan Dollar"),
    TZS ( "TZS - Tanzanian Shilling"),
    THB ( "THB - Thai Baht"),
    TOP ( "TOP - Tongan Paʻanga"),
    TTD ( "TTD - Trinidad and Tobago Dollar"),
    TND ( "TND - Tunisian Dinar"),
    TRY ( "TRY - Turkish Lira"),
    TMT ( "TMT - Turkmenistan Manat"),
    AED ( "AED - United Arab Emirates Dirham"),
    UGX ( "UGX - Ugandan Shilling"),
    UAH ( "UAH - Ukrainian Hryvnia"),
    UYU ( "UYU - Uruguayan Peso"),
    UZS ( "UZS - Uzbekistani Som"),
    VUV ( "VUV - Vanuatu Vatu"),
    VEF ( "VEF - Venezuelan Bolívar"),
    VND ( "VND - Vietnamese Đồng"),
    XOF ( "XOF - West African CFA Franc"),
    YER ( "YER - Yemeni Rial"),
    ZMW ( "ZMW - Zambian Kwacha"),
    ZWL ( "ZWL - Zimbabwean Dollar");


    private String description;

    Currency(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
